---
- hosts: "{{ project }}.lxc"
  remote_user: root
  tasks:
    - name: System Requirement
      include: tasks/system.yml
    - name: Drupal Installation
      include: tasks/drupal-install.yml project={{ project }} project_url={{ project_url }} drupal_profile={{ drupal_profile }}
    #- name: Initialize the project into the git repository
    #  include: tasks/init-git.yml gitpath={{ gitpath }}
  ###################
  # Handlers
  ###################
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted enabled=yes
    - name: restart varnish
      service: name=varnish state=restarted enabled=yes
