---
- hosts: "{{ project }}.lxc"
  remote_user: root
  vars:
    project: "{{ project }}"
    project_path: "/home/{{ user_name }}/{{ project }}"
    user_name: "{{ user_name }}"
  tasks:
    - name: Install the system packages
      include: tasks/system.yml
    - name: Install a Drupal website
      include: tasks/drupal-install.yml
    - name: Initialize the project into the git repository
      include: tasks/init-git.yml gitpath={{ gitpath }}
      when: gitpath is defined
  ###################
  # Handlers
  ###################
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted enabled=yes
    - name: restart varnish
      service: name=varnish state=restarted enabled=yes
