- name: Activate vhost
  file: src=/home/smile/{{ project }}/conf/apache/{{ project_url }}.conf dest=/etc/apache2/sites-enabled/{{ project_url }}.conf state=link

- name: Remove default php.ini
  file: path=/etc/php5/cli/php.ini
        state=absent

- name: Link php.ini file
  file: src=/home/smile/{{ project }}/conf/php/php.ini dest=/etc/php5/cli/php.ini state=link

- name: Remove default site config
  file: path=/etc/apache2/ports.conf
        state=absent

- name: Link ports.conf file
  file: src=/home/smile/{{ project }}/conf/apache/ports.conf dest=/etc/apache2/ports.conf state=link
  notify:
  - restart apache2
