- name: Activate vhost
  file: src={{ project_path }}/conf/apache/{{ project_url }}.conf dest=/etc/apache2/sites-enabled/{{ project_url }}.conf state=link

- name: Symlink php.ini apache2
  file: src={{ project_path }}/conf/php/apache2/php.ini dest=/etc/php/7.0/apache2/php.ini state=link

- name: Remove default site config
  file: path=/etc/apache2/ports.conf
        state=absent

- name: Link ports.conf file
  file: src={{ project_path }}/conf/apache/ports.conf dest=/etc/apache2/ports.conf state=link

- name: Enable apache modules
  shell: a2enmod rewrite expires headers

- name: Restart apache immediately to avoid varnish trying to steal apache port
  service: name=apache2 state=restarted enabled=yes
