- name: Define Apache ports
  include: tasks/apache-configuration.yml apache_port={{ apache_port }}

- name: Configure Varnish if needed
  include: tasks/varnish-configuration.yml varnish_port={{ varnish_port }}
  when: varnish_port != "0"

- name: Configure Nginx if needed
  include: tasks/nginx-configuration.yml
  when: varnish_port != "0"

- name: drupal drush root folder
  file: path=/root/.drush state=directory

- name: drupal drush user folder
  file: path=/home/{{ user_name }}/.drush state=directory

- name: Symlink alias root
  file: src={{ project_path }}/conf/drupal/drush/aliases.drushrc.php dest=/root/.drush/aliases.drushrc.php state=link

- name: Symlink alias for the user
  file: src={{ project_path }}/conf/drupal/drush/aliases.drushrc.php dest=/home/{{ user_name }}/.drush/aliases.drushrc.php state=link

- name: Symlink php.ini cli
  file: src={{ project_path }}/conf/php/cli/php.ini dest=/etc/php/7.0/cli/php.ini state=link

- name: Add write rights on settings.php for installation
  file: path=/var/www/{{ project }}/web/sites/default/settings.php mode=0776

- name: install website
  command: drush @dev  site-install {{ drupal_profile }} --db-su="root" --db-su-pw="" --account-name=admin --account-pass=admin --db-url=mysql://{{ project }}:{{ project }}@localhost:3306/{{ project }} -y

- name: Include the local settings file 
  lineinfile:
    dest: /var/www/{{ project }}/web/sites/default/settings.php
    line: "\nif (file_exists(__DIR__ . '/settings.local.php')) {\n  include __DIR__ . '/settings.local.php';\n}"

- name: Remove write rights on settings.php after installation
  file: path=/var/www/{{ project }}/web/sites/default/settings.php mode=0774

- name: Remove default site config setting
  file: path=/var/www/{{ project }}/web/sites/settings.local.php
            state=absent
- name: Remove default site config services
  file: path=/var/www/{{ project }}/web/sites/local.services.yml
            state=absent 

- name: Symlink settings drupal
  file: src={{ project_path }}/conf/drupal/default/settings.local.php dest=/var/www/{{ project }}/web/sites/default/settings.local.php state=link

- name: Symlink services drupal
  file: src={{ project_path }}/conf/drupal/default/local.services.yml dest=/var/www/{{ project }}/web/sites/default/local.services.yml state=link

- name: Remove drupal files folder
  file: path=/var/www/{{ project }}/web/sites/default/files
            state=absent

- name: Symlink drupal files folder
  file: src={{ project_path }}/data/files dest=/var/www/{{ project }}/web/sites/default/files state=link

- name: Correct permissions
  shell: bash {{ project_path }}/scripts/fix-perms.sh

#- name: Symlink sites drupal
#  file: src={{ project_path }}/conf/drupal/sites.php dest=/var/www/html/{{ project }}/sites/sites.php state=link
