- name: Install drupal
  shell: composer create-project drupal-composer/drupal-project:8.x-dev {{ project }} creates=/var/www/{{ project }}
  tags: composer

- name: Move drupal to correct location
  shell: mv {{ project }} /var/www/ creates=/var/www/{{ project }} creates=/var/www/{{ project }}

- name: Initialize Drupal Project
  include: tasks/init-project.yml project={{ project }}

- name: Deploy Drupal Website
  include: tasks/deploy-drupal.yml drupal_profile={{ drupal_profile }}
