- stat: path=/var/www/{{ project }}
  register: drupal_directory
- name: Install drupal
  composer:
    command: "create-project"
    arguments: "drupal-composer/drupal-project:8.x-dev {{ project }}"
    working_dir: "/var/www"
  when: drupal_directory.stat.exists == False

- name: Initialize Drupal Project
  include: tasks/init-project.yml project={{ project }}

- name: Deploy Drupal Website
  include: tasks/deploy-drupal.yml drupal_profile={{ drupal_profile }}
