##############################
# Initialize Drupal project  #
##############################
- name: Create project directory
  file: path=/home/smile/{{ project }} state=directory
- name: Create conf directory
  file: path=/home/smile/{{ project }}/conf state=directory
- name: Create apache conf directory
  file: path=/home/smile/{{ project }}/conf/apache state=directory
- name: Create varnish conf directory
  file: path=/home/smile/{{ project }}/conf/varnish state=directory
- name: Create php conf directory
  file: path=/home/smile/{{ project }}/conf/php state=directory
- name: Create php/cli conf directory
  file: path=/home/smile/{{ project }}/conf/php/cli state=directory
- name: Create php/apache2 conf directory
  file: path=/home/smile/{{ project }}/conf/php/apache2 state=directory

- name: Setup php cli for our app
  template: src=templates/drupal/conf/php/cli/php.ini dest=/home/smile/{{ project }}/conf/php/cli/php.ini

- name: Setup php apache2 for our app
  template: src=templates/drupal/conf/php/apache2/php.ini dest=/home/smile/{{ project }}/conf/php/apache2/php.ini

- name: Setup apache config for our app
  template: src=templates/drupal/conf/apache/project.conf dest=/home/smile/{{ project }}/conf/apache/{{ project_url }}.conf

- name: Define apache ports
  template: src=templates/drupal/conf/apache/ports.conf dest=/home/smile/{{ project }}/conf/apache/ports.conf

- name: drupal sources folder
  file: path=/home/smile/{{ project }}/conf/drupal state=directory

- name: drupal default site folder
  file: path=/home/smile/{{ project }}/conf/drupal/default state=directory

- name: drupal drush folder
  file: path=/home/smile/{{ project }}/conf/drupal/drush state=directory

- name: default site settings
  template: src=templates/drupal/conf/drupal/default/settings.local.php dest=/home/smile/{{ project }}/conf/drupal/default/settings.local.php

- name: local services
  template: src=templates/drupal/conf/drupal/default/local.services.yml dest=/home/smile/{{ project }}/conf/drupal/default/local.services.yml

- name: drush aliases
  template: src=templates/drupal/conf/drupal/drush/aliases.drushrc.php dest=/home/smile/{{ project }}/conf/drupal/drush/aliases.drushrc.php

- name: Source directory
  file: path=/home/smile/{{ project }}/src/sites/all/modules/custom state=directory

- name: Script directory
  file: path=/home/smile/{{ project }}/scripts state=directory

- name: drupal data folder
  file: path=/home/smile/{{ project }}/data state=directory

- name: drupal files folder
  file: path=/home/smile/{{ project }}/data/files state=directory

- name: drupal translations folder
  file: path=/home/smile/{{ project }}/data/files/translations state=directory

- name: env script
  template: src=templates/drupal/scripts/env.sh dest=/home/smile/{{ project }}/scripts/env.sh

- name: fix-perms script
  template: src=templates/drupal/scripts/fix-perms.sh dest=/home/smile/{{ project }}/scripts/fix-perms.sh

- name: rebuild script
  template: src=templates/drupal/scripts/rebuild.sh dest=/home/smile/{{ project }}/scripts/rebuild.sh

- name: update script
  template: src=templates/drupal/scripts/update.sh dest=/home/smile/{{ project }}/scripts/update.sh

