- name: install python-apt
  raw: apt-get update && apt-get install python-apt -y -q
- name: apt-get update
  apt:  update_cache=yes
###################
# Misc. tools
###################
- name: Install usefull system tools
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-dev
    - python-pip
    - curl
    - build-essential
    - gcc

###################
# REDIS
###################
- name: Install Redis-server
  apt: name=redis-server state=present
  when: redis-required is defined

###################
# Apache2
###################
- name: Remove default site config
  file: path=/etc/apache2/sites-enabled/000-default.conf
        state=absent

###################
# Varnish
###################
- name: Install Redis-server
  apt: name=varnish state=present
  when: varnish_port is defined

###################
# composer
###################
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: composer

# Install composer globally
- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: composer

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: composer

###################
# drush
###################

- name: install drush
  shell: php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > /usr/local/bin/drush creates=/usr/local/bin/drush

- name: make drush executable
  file: path=/usr/local/bin/drush mode=a+x state=file
